Feat: Modal when the user is connected in a wrong network.
decentraland/decentraland-dapps pull request #129
Opened 2021-04-09 15:45 UTC by malaniz

Feat: Modal when the user is connected in a wrong network.
![img-7zM0xx_000](https://user-images.githubusercontent.com/477970/114206173-74fb3700-9931-11eb-966a-c34cc9a5c70c.png)

2021-04-19 14:22 UTC, nicosantangelo requested changes
I understand that we're using the base components from decentraland-UI but we still need to adjust margins and paddings a bit

![image](https://user-images.githubusercontent.com/692077/115248967-8cd77580-a0fe-11eb-8686-3e0da7226343.png)

2021-04-19 14:22 UTC, nicosantangelo commented on src/modules/translation/defaults/en.json
> +        "message": "You need to be connected to {expectedChainName} Network to use this app, but you are currently connected to {currentChainName} Network."
```suggestion
        "message": "You need to be connected to the {expectedChainName} Network to use this app, but you are currently connected to {currentChainName}."
```

2021-04-19 14:22 UTC, nicosantangelo commented on src/containers/Navbar/Navbar.types.tsx
> +export declare type WrongNetworkModalI18N = {
```suggestion
export type WrongNetworkModalI18N = {
```

2021-05-06 16:32 UTC, nachomazzara approved these changes

2021-05-06 22:04 UTC, merged

2021-05-06 22:06 UTC, cazala commented
:tada: This PR is included in version 11.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/decentraland-dapps/v/11.0.0)
- [GitHub release](https://github.com/decentraland/decentraland-dapps/releases/tag/v11.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: