feat: sale price too low toast error
decentraland/decentraland-dapps pull request #229
Opened 2022-04-19 19:45 UTC by nicosantangelo

Shows a toast modal error when the price of the meta transaction sale is too low
Closes #226

2022-04-21 18:20 UTC, LautaroPetaccio requested changes
It seems that the `package-lock.json` changed, but there are no dependencies being updates in the `package.json`, I think that you're missing them.

2022-04-21 18:20 UTC, LautaroPetaccio commented on src/modules/toast/sagas.spec.ts
> +    it('should show an unknown error toast', () => {
```suggestion
    it('should show a sales price too low error toast', () => {
```

2022-04-21 20:08 UTC, nicosantangelo commented
Thanks for the review peta <3

2022-04-22 14:14 UTC, LautaroPetaccio approved these changes

2022-04-22 15:51 UTC, merged

2022-04-22 15:54 UTC, cazala commented
:tada: This PR is included in version 12.43.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/decentraland-dapps/v/12.43.0)
- [GitHub release](https://github.com/decentraland/decentraland-dapps/releases/tag/v12.43.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: