feat: Open MANA-FIAT Gateway Request Flow + No wallet address in wiget url
decentraland/decentraland-dapps pull request #304
Opened 2022-12-08 17:35 UTC by kevinszuchet

2022-12-09 12:58 UTC, LautaroPetaccio requested changes

2022-12-09 12:58 UTC, LautaroPetaccio commented on src/modules/manaFiatGateway/sagas.ts
> +      // TODO (sign url): what does happen if the request fail?
Ideally, we should have an action to start a loading screen for the request and success and failure actions accordingly to notify the UI of what's going on.

2022-12-09 17:09 UTC, LautaroPetaccio requested changes

2022-12-09 17:09 UTC, LautaroPetaccio commented on src/modules/manaFiatGateway/sagas.ts
> +    yield put(openManaFiatGatewaySuccess())
Would you mind adding saga tests that exercise the put of the `openManaFiatGatewaySuccess` and `openManaFiatGatewayFailure` actions?

2022-12-09 17:39 UTC, LautaroPetaccio approved these changes

2022-12-09 17:39 UTC, LautaroPetaccio commented on src/modules/manaFiatGateway/reducer.spec.ts
> +  it('should update data and remove the request action from the loading state', () => {
```suggestion
  it('should remove the request action from the loading state and remove the error', () => {
```

2022-12-12 15:41 UTC, fzavalia requested changes

2022-12-12 15:41 UTC, fzavalia commented on src/modules/manaFiatGateway/moonpay/MoonPay.spec.ts
> +  describe.only('when build the widget url', () => {
Remove only

2022-12-12 15:44 UTC, juanmahidalgo commented on src/modules/manaFiatGateway/sagas.ts
> +        const transak = new Transak(transakConfig, address, network)
```suggestion
        const address: string = yield select(getAddress)
        const transak = new Transak(transakConfig, address, network)
```
I'd move the address selector to the `transak` case now that the moonpay one won't use it anymore, wdyt?

2022-12-12 16:43 UTC, fzavalia approved these changes

2022-12-12 16:44 UTC, merged